PythonSecondPart/urls.py
from django.contrib import admin
from django.urls import path

import myCrudApp.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api', myCrudApp.views.index, name="home"),

    path('api/university/create', myCrudApp.views.create_university, name="home"),
    path('api/university/edit/<int:id>', myCrudApp.views.edit_university_by_id, name="home"),
    path('api/university/delete/<int:id>', myCrudApp.views.delete_university_by_id, name="home"),
    path('api/university', myCrudApp.views.get_all_university, name="home"),

    path('api/student/create', myCrudApp.views.create_student, name="home"),
    path('api/student/edit/<int:id>', myCrudApp.views.edit_student_by_id, name="home"),
    path('api/student/delete/<int:id>', myCrudApp.views.delete_student_by_id, name="home"),
    path('api/student', myCrudApp.views.get_all_student, name="home")
]

myCrudApp/urls.py
from django.urls import path
from myCrudApp import views

urlpatterns = [
    #Вызовет views.index при открытии главной страницы сайта
    path('', "Test", name="home")
]

myCrudApp/models.py
from django.db import models


class University(models.Model):
    full_name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=10)
    date_of_creation = models.DateField()

    def __str__(self):
        return f"{self.full_name}_{self.short_name}_{self.date_of_creation}"


class Student(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    FCs = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    year_of_admission = models.DateField()

    def __str__(self):
        return f"{self.FCs}_{self.date_of_birth}_{self.year_of_admission}_{self.university.id}"

myCrudApp/forms.py
from django import forms

from myCrudApp.models import University, Student


class DateInput(forms.DateInput):
    input_type = 'date'


class UniversityForm(forms.ModelForm):

    class Meta:
        model = University
        fields = '__all__'
        widgets = {
            'date_of_creation': DateInput()
        }


class StudentForm(forms.Form):
    model = Student
    fields = '__all__'

myCrudApp/views.py
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.template.response import TemplateResponse

from myCrudApp.forms import UniversityForm, StudentForm
from myCrudApp.models import University, Student


def index(request):
    return TemplateResponse(request, "index.html")


def create_university(request):
    if request.method == "POST":
        full_name = request.POST.get("full_name")
        short_name = request.POST.get("short_name")
        date_of_creation = request.POST.get("date_of_creation")
        University.objects.create(
            full_name=full_name,
            short_name=short_name,
            date_of_creation=date_of_creation
        )
        return HttpResponseRedirect(f"/api/university")
    if request.method == "GET":
        data = {"form": UniversityForm()}
        return TemplateResponse(request, "createUniversity.html", data)


def edit_university_by_id(request, id):
    if request.method == "GET":
        university = University.objects.get(id=id)
        data = {"university": university}
        return TemplateResponse(request, "createUniversity.html", data)
    if request.method == "POST":
        full_name = request.POST.get("full_name")
        short_name = request.POST.get("short_name")
        date_of_creation = request.POST.get("date_of_creation")
        University.objects.filter(id=id).update(
            full_name=full_name,
            short_name=short_name,
            date_of_creation=date_of_creation
        )
        return HttpResponseRedirect(f"/api/university")


def delete_university_by_id(request, id):
    if request.method == "GET":
        try:
            product = University.objects.get(id=id)
            product.delete()
            return HttpResponseRedirect("/api/university")
        except University.DoesNotExist:
            return HttpResponseNotFound("Университета с таким id не существует")


def get_all_university(request):
    if request.method == "GET":
        university_list = University.objects.all()
        data = {"universities": university_list}
        return TemplateResponse(request, "allUniversity.html", data)


def create_student(request):
    if request.method == "POST":
        student = Student()
        student.FCs = request.POST.get("FCs")
        student.date_of_birth = request.POST.get("date_of_birth")
        student.year_of_admission = request.POST.get("year_of_admission")
        student.university_id = request.POST.get("university")
        student.save()
        return HttpResponseRedirect(f"/api/student")
    if request.method == "GET":
        available_university_list = University.objects.all()
        data = {
            "student": StudentForm(),
            "available_university_list": available_university_list
        }
        return TemplateResponse(request, "createStudent.html", data)


def edit_student_by_id(request, id):
    if request.method == "GET":
        student = Student.objects.get(id=id)
        available_university_list = University.objects.all()
        data = {
            "student": student,
            "available_university_list": available_university_list
        }
        return TemplateResponse(request, "createStudent.html", data)
    if request.method == "POST":
        student = Student()
        student.FCs = request.POST.get("FCs")
        student.date_of_birth = request.POST.get("date_of_birth")
        student.year_of_admission = request.POST.get("year_of_admission")
        student.university_id = request.POST.get("university")
        University.objects.filter(id=id).update(student=student)
        return HttpResponseRedirect(f"/api/student")


def delete_student_by_id(request, id):
    if request.method == "GET":
        try:
            product = Student.objects.get(id=id)
            product.delete()
            return HttpResponseRedirect("/api/student")
        except University.DoesNotExist:
            return HttpResponseNotFound("Студента с таким id не существует")


def get_all_student(request):
    if request.method == "GET":
        student_list = Student.objects.all()
        data = {"students": student_list}
        return TemplateResponse(request, "allStudent.html", data)

myCrudApp/templates/allStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>student</title>
</head>
<body>
<a href="student/create">Добавить Студента</a>
    <h2>Список Студентов</h2>
    <table>
        <thead>
        <th>Id</th>
        <th>ФИО</th>
        <th>Дата рождения</th>
        <th>Дата поступления</th>
        <th>Короткое название университета</th>
        <th></th>
        <th></th>
        </thead>
        {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.FCs }}</td>
                <td>{{ student.date_of_birth|date:"Y-m-d" }}</td>
                <td>{{ student.year_of_admission|date:"Y-m-d" }}</td>
                <td>{{ student.university.short_name }}</td>
                <td><a href="student/delete/{{ student.id }}">Удалить</a></td>
                <td><a href="student/edit/{{ student.id }}">Изменить</a></td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>

myCrudApp/templates/allUniversity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>university</title>
</head>
<body>
<a href="university/create">Добавить Университет</a>
    <h2>Список Университетов</h2>
    <table>
        <thead>
        <th>Id</th>
        <th>Название</th>
        <th>Короткое название</th>
        <th>Дата создания</th>
        <th></th>
        <th></th>
        </thead>
        {% for university in universities %}
            <tr>
                <td>{{ university.id }}</td>
                <td>{{ university.full_name }}</td>
                <td>{{ university.short_name }}</td>
                <td>{{ university.date_of_creation|date:"Y-m-d" }}</td>
                <td><a href="university/delete/{{ university.id }}">Удалить</a></td>
                <td><a href="university/edit/{{ university.id }}">Изменить</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

myCrudApp/templates/createStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>student</title>
</head>
<body>
<table>
    <h1>Student</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            <tbody>
            <tr>
                <th><label for="id_FCs">Full name:</label></th>
                <td>
                    <input type="text" name="FCs" maxlength="50" required="" id="id_FCs"
                           value="{{ student.FCs }}">
                </td>
            </tr>
            <tr>
                <th><label for="id_date_of_birth">Date of birth:</label></th>
                <td>
                    <input type="date" name="date_of_birth" required="" id="id_date_of_birth"
                           value="{{ student.date_of_birth|date:"Y-m-d" }}">
                </td>
            </tr>
            <tr>
                <th><label for="id_year_of_admission">Year of admission:</label></th>
                <td>
                    <input type="date" name="year_of_admission" required="" id="id_year_of_admission"
                           value="{{ student.year_of_admission|date:"Y-m-d" }}">
                </td>
            </tr>
            <tr>
                <th><label for="id_university">University:</label></th>
                <td>
                    <select name="university" required="" id="id_university">
                        {% for university in available_university_list %}
                            <option value="{{ university.id }}">{{ university.short_name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            </tbody>
        </table>
        <input type="submit" value="confirm">
    </form>
</table>
</body>
</html>


{% comment %}
<select name="item_id">
{% for entry in items %}
    <option value="{{ entry.id }}">{{ entry.name }}</option>
{% endfor %}
</select>{% endcomment %}

myCrudApp/templates/createUniversity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>university</title>
</head>
<body>
<table>
    <h1>University</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            <tbody>
            <tr>
                <th><label for="id_full_name">Full name:</label></th>
                <td>
                    <input type="text" name="full_name" maxlength="50" required="" id="id_full_name"
                           value="{{ university.full_name }}">
                </td>
            </tr>
            <tr>
                <th><label for="id_short_name">Short_name:</label></th>
                <td>
                    <input type="text" name="short_name" maxlength="10" required="" id="id_short_name"
                           value="{{ university.short_name }}">
                </td>
            </tr>
            <tr>
                <th><label for="id_date_of_creation">Date of creation:</label></th>
                <td>
                    <input type="date" name="date_of_creation" required="" id="id_date_of_creation"
                           value="{{ university.date_of_creation|date:"Y-m-d" }}">
                </td>
            </tr>
            </tbody>
        </table>
        <input type="submit" value="confirm">
    </form>
</table>
</body>
</html>

myCrudApp/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Index</title>
</head>
<body>
<h1>Endpoints:</h1>
<div style="margin-left: 20px">
    <h2>University:</h2>
    <div style="margin-left: 40px">
        <h4>POST: api/university/create - create new university</h4>
        <h4>GET: api/university/create - get create university page</h4>
        <h4>GET: api/university - get all universities</h4>
        <h4>GET: api/university/{id} - get university by id</h4>
        <h4>GET: api/university/delete/{id} - delete university by id</h4>
        <h4>GET: api/university/edit/{id} - get edit university page</h4>
        <h4>POST: api/university/edit/{id} - edit university by id</h4>
    </div>
</div>
<div style="margin-left: 20px">
    <h2>Student:</h2>
    <div style="margin-left: 40px">
        <h4>POST: api/create-student - create new student</h4>
        <h4>GET: api/create-student - get create student page</h4>
        <h4>GET: api/student - get all students</h4>
        <h4>GET: api/student/{id} - get student by id</h4>
        <h4>DELETE: api/student/{id} - delete student by id</h4>
        <h4>PATCH: api/student/{id} - edit student by id</h4>
    </div>
</div>
</body>
</html>